### ISSUE TITLE
Investigate direct support for git-bash in Windows

### ISSUE THREAD

**Issue by Zordrak** [tfutils/tfenv#144]
See #140

**Comment by Zordrak** [comment]
@stephengroat at first glance, the failure is symlink related.

My recent experience with git-bash is that symlinking cannot be trusted even when support is explicitly installed.

Needs some deeper investigation to see if it can be made to function reliably.

**Comment by sworisbreathing** [comment]
I haven't looked at the travis result but I just installed it in git bash on windows and so far it seems to work. There's an issue with [tf-install](https://github.com/tfutils/tfenv/blob/master/libexec/tfenv-install#L239) because git bash struggles with the type of stdin redirection used in the read loop. Since that loop is only logging outputs it doesn't seem to break anything as far as actual functionality

**Comment by stephengroat** [comment]
@Zordrak after merging `master`, all tests pass now for windows
