### ISSUE TITLE
Terraform wrapper script fails all the time

### ISSUE THREAD

**Issue by ruionwriting** [tfutils/tfenv#155]
Since the 45da04ade6a69ebd79b28b8f8b84974a79400fb5 every time I call `terraform` it's simply broken:

```bash
/usr/local/bin/terraform: line 24: /usr/local/lib/helpers.sh: No such file or directory
[ERROR] Failed to source helpers from /usr/local/lib/helpers.sh
```

Looks to be any issue on the Bash code and very recent. I'm sure this was working last week.

Ubuntu/Bionic is the OS I'm using this. I'm now pining to `v1.0.2` as I should have done from the very start.

**Comment by Zordrak** [comment]
How do you install tfenv?

This error indicates your TFENV_ROOT is set to /usr/local rather than, e.g. /usr/local/tfenv or /opt/tfenv. The terraform script is being called from a bin directory where it expects to find a lib directory next to it containing the logging and helpers scripts.

Yes indeed master is now at 2.0.0-alpha2 and is in testing for a v2 release. Production workloads should use the latest v1 release.

I will shortly arrange a v1 branch for those checking out directly, however I recommend using release tags or tarballs.

**Comment by Zordrak** [comment]
I see what's happening. You've got a symlink from /usr/local/bin/terraform to your tfenv installation rather than adding your TFENV bin directory to your path.

This should be a supported approach, I've just not accounted for it properly in the helper loading. I will try to address this now and get an alpha3 out shortly with a fix.

**Comment by Zordrak** [comment]
Yep, I totally see what I've done. Fix on it's way.

**Comment by Zordrak** [comment]
@ruionwriting This should all be sorted out by #156 

I'd really appreciate you testing 2.0.0-alpha3 and seeing if the problem is now resolved, and whether you encounter any other issues.
