### ISSUE TITLE
0.11.15-oci build should not be installed

### ISSUE THREAD

**Issue by phils** [tfutils/tfenv#173]
Hi there.. I see that a fix was put in some that the 0.11.15-oci build would be detected and installed.

However, Hashicorp says this was an internal build not for general use, so I don't think tfenv should be detecting it.

https://discuss.hashicorp.com/t/what-is-the-status-of-terraform-v0-11-15/3340

Reproducer for issue:

tfenv install latest:^0.11

**Comment by Zordrak** [comment]
You are right; based upon the information provided, 0.11.15-oci should be treated like a pre-release and should not be installed by latest keyword, only by explicit request.

However, I am hesitant to make the change at this point because of the effect it will have on existing users. Since the latest has been picking up 0.11.15-oci for a significant period of time, changing tfenv to no longer install it with the latest keyword would break all usage that currently uses `latest:^0.11.` forcing users to update their configurations to either specify 0.11.15-oci, or manually fix their tfstate files to revert them to 0.11.14.

Given that use of 0.11.15-oci seems prevelant and without problems, and that Martin confirms `it does not include any harmful changes`, and that new users should be defaulting to >=0.12, changing the tfenv behaviour now would be more harmful than helpful in my opinion.
