### ISSUE TITLE
min-required not correct for base with sub-modules

### ISSUE THREAD

**Issue by mcaulifn** [tfutils/tfenv#225]
When a base module and sub-modules all define a `required_version`, the first found is used rather than the highest of the list.

Given the following module/sub-modules:
```sh
.
├── modules
│   ├── dependencies
│   │   ├── providers.tf
│   │   └── versions.tf  # set to "~>0.13"
│   ├── managed
│   │   ├── providers.tf
│   │   └── versions.tf  # set to "~>0.13"
│   ├── rds
│   │   ├── locals.tf
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   ├── secrets.tf
│   │   ├── variables.tf
│   │   └── versions.tf  # set to "~>0.13"
├── config.tf
├── data.tf
├── locals.tf
├── providers.tf
├── variables.tf
└── versions.tf  # set to ">=0.14"
```

Running `min-required` with `-x` will output the following:
```sh
+ versions='   = ~> 0.13   = ~> 0.13   = ~> 0.13   = >= 0.14'
+ [[    = ~> 0.13   = ~> 0.13   = ~> 0.13   = >= 0.14 =~ ([~=!<>]{0,2}[[:blank:]]*[0-9]+[0-9.]+)[^0-9]* ]]
+ found_min_required='~> 0.13'
```

Changing the version in `modules/dependencies/versions.tf` to `~>0.14` will result in:
```sh
versions='   = ~> 0.14   = ~> 0.13   = ~> 0.13   = >= 0.14'
found_min_required='~> 0.14'
```

Changing the version in `modules/dependencies/versions.tf` to `~>0.12` will result in:
```sh
versions='   = ~> 0.12   = ~> 0.13   = ~> 0.13   = >= 0.14'
found_min_required='~> 0.12'
```

**Comment by Zordrak** [comment]
This explicitly presumes that you store modules in a subdirectory within your root module. I think the problem here is that we are recursively testing subdirectories when we should not be.

If your root module is calling another module with a higher required minimum version, then your root module implicitly requires that version and should have its minimum version set accordingly. tfenv is not in a position to determine the minimum version of all possible module sources, whether stored locally on disk, within the same directory as the root component or elsewhere, or stored in an external git repository or registry. It can only depend on the root module informing as to the minimum version necessary for all dependent modules.

In your case, storing the modules in a subdirectory of the root module, tfenv is inappropriately querying your other module version files, and I think should be restricted to querying files in the root module directory.

I am slightly concerned however as to resolving this causing a breaking change for existing implementations, although it probably should still be fixed.
