### ISSUE TITLE
How to install 0.13.5?

### ISSUE THREAD

**Issue by asychev** [tfutils/tfenv#265]
Hi!

```
$ tfenv --version
tfenv 2.2.1
```

I need to use 0.13.5 version, but seems like it is not possible to install it with tfenv now:

```
$ tfenv install 0.13.7
Installing Terraform v0.13.7
Downloading release tarball from https://releases.hashicorp.com/terraform/0.13.7/terraform_0.13.7_darwin_amd64.zip
######################################################################################################################################################################################################################################################## 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.13.7/terraform_0.13.7_SHA256SUMS
Downloading SHA hash signature file from https://releases.hashicorp.com/terraform/0.13.7/terraform_0.13.7_SHA256SUMS.sig
▶ INFO Identifying hashicorp
✔ <followed> public key fingerprint: C874 011F 0AB4 0511 0D02 1055 3436 5D94 72D7 468F
You last followed hashicorp on 2021-05-04 11:13:35 CEST
✔ <followed> admin of DNS zone hashicorp.com: found TXT entry keybase-site-verification=a-iv8bbkw3LgvmnT-p1jJ7Com9O-5GrOyFClq2-0iRQ [cached 2021-05-04 11:13:00 CEST]
Signature verified. Signed by hashicorp 1 week ago (2021-04-26 22:27:01 +0200 CEST).
PGP Fingerprint: c874011f0ab405110d02105534365d9472d7468f.
Archive:  tfenv_download.iZjxsk/terraform_0.13.7_darwin_amd64.zip
  inflating: /usr/local/Cellar/tfenv/2.2.1/versions/0.13.7/terraform
Installation of terraform v0.13.7 successful. To make this your default version, run 'tfenv use 0.13.7'
```

```
$ tfenv install 0.13.5
Installing Terraform v0.13.5
Downloading release tarball from https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_darwin_amd64.zip
######################################################################################################################################################################################################################################################## 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_SHA256SUMS
Downloading SHA hash signature file from https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_SHA256SUMS.sig
▶ ERROR openpgp: signature made by unknown entity
SHA256SUMS signature does not match!
```

Unfortunately, I can't figure out how to solve this. Any ideas?

**Comment by pol** [comment]
This kind of sucks, but because the signatures are no longer valid/trusted, the safest thing for tfenv to do is to reject the binary.  From its perspective there is no difference between what it is getting and a malicious fake terraform binary that will pwn your system.  So tfenv is doing the right thing!  

That said, if you want a workaround, then you can: 
1. `cd /usr/local/Cellar/tfenv/2.2.1/versions/`
2. `mkdir <version>`
3. navigate to the release you want here: https://releases.hashicorp.com/terraform/
4. download the correct zip file into your version folder and unzip it (after which you can delete the zip file). 
5. you should now have a `/usr/local/Cellar/tfenv/2.2.1/versions/<new version>/terraform` binary
6. you should be able to select that version of terraform now with tfenv. 

They might make this easier with a `--force` or `--ignore-sig` or something like that.  But really hashicorp needs to re-sign all of their old releases with the new key.  

Given the security situation, the safest option is to upgrade your version of terraform to a trusted binary (in your case, that would be 0.13.7), and consider the older ones sus. :)

**Comment by asychev** [comment]
Thanks for the explanation, clear now, indeed tfenv do right thing ;)
