### ISSUE TITLE
Any chance of a new release?

### ISSUE THREAD

**Issue by aston-r** [tfutils/tfenv#295]
@Zordrak 

There's been lots of great PRs merged over the last few months. Could you please release the new version?

**Comment by richid** [comment]
I'm very much interested in a new release. Specifically, I'm eager to get [this fix](https://github.com/tfutils/tfenv/pull/126) since the `min-required` functionality is broken if you use the pessimistic constraint operator like so: `required_version = "~> 1.0"`

Thanks for this great little utility!

**Comment by OJFord** [comment]
https://github.com/tfutils/tfenv/tree/v2.2.3 has been released since this issue was opened (not long after richid's comment) - there's been nothing merged (or any maintainer activity afaict) since then.

**Comment by Sickafant** [comment]
Hi @Zordrak , thanks for this tool. I'd really like to use `latest-required`, wasn't sure how best to find out what the plans for future releases are.
