### ISSUE TITLE
tfenv can't see installed terraform versions after upgrade.

### ISSUE THREAD

**Issue by Chris-Leeworthy** [tfutils/tfenv#325]
Running on MacOS Monterey v12.2.1.

I ran a `brew upgrade` to upgrade the packages on my machine.

Since then `tfenv` failed to show any of the Terraform versions I had installed on my machine. 

Have they been removed during the upgrade?  If so it seems bad that every upgrade essentially destroys my existing setup.

**Comment by jjmartres** [comment]
I got the issue. I also have a lot of 403 error:

```
$ tfenv install 0.15.0 
Installing Terraform v0.15.0
Downloading release tarball from https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_darwin_arm64.zip
curl: (22) The requested URL returned error: 403                                                                                                                                       

Tarball download failed
```

**Comment by brandon-welsch** [comment]
`0.15.0` version doesn't exist for darwin with arm64 processor. The first release of Terraform that provide an arm64 binary is `1.0.2`.

You can see it here: https://releases.hashicorp.com/terraform/1.0.2/

**Comment by adampeklay** [comment]
@brandon-welsch That worked for me, thanks!

**Comment by Rooks103** [comment]
I'm seeing a similar thing as @Chris-Leeworthy. Recently ran a brew upgrade and just came back to tfenv to do some testing, and now I'm seeing no versions installed. 

Even worse for me, when I try to run others commands, it just hangs. Tried `tfenv list-remote` and `tfenv install 1.0.8` so far. `tfenv init` ran, but didn't seem to do anything. I then tried a quick uninstall / install through brew which didn't seem to fix anything. Guessing some leftover remnant from a previous versions is breaking stuff, but that's a completely random guess at this point. Will update if I get this working, but any help is appreciated.

**Comment by requix** [comment]
I got the same issue after `brew upgrade`.
As a workaround, if you need an old terraform version, use `export TFENV_ARCH=amd64`

**Comment by bryanhiestand** [comment]
It seems like this is two slightly different and related issues.  The combination makes for a nasty breaking change for anyone using tfenv to run older versions of terraform on Darwin ARM64.
1. #280 does not handle versions prior to `1.0.2`, so tfenv `2.2.3` is now unusable for them.

A few things could be done to address this: adding a compatibility mode that installs amd64 instead on older versions, pulling amd64 instead of arm64 if you get a 403 (idk why they're doing that instead of 404), Hashicorp uploading arm64 binaries for older versions, or <better idea here>? I hate to hard-code version checks into install logic, but barring any better ideas, I could PR that for the next version of tfenv?

@requix's suggestion above helps address this on the install side.  And with `GODEBUG=asyncpreemptoff=1` ([credit](https://yaleman.org/post/2021/2021-01-01-apple-m1-terraform-and-golang/)), amd64 versions of terraform mostly work under Rosetta.

2. old copies of terraform get deleted by the upgrade (the original post)
I haven't dug into this, but it looks like it might be homebrew automatically cleaning up old versions under the cellar path. Unfortunately, that deletes the old terraform binaries. This wouldn't be a huge deal if it were easy to re-install them, but with the breaking change above, it's unfortunate.

**Comment by Chris-Leeworthy** [comment]
For what it's worth I'm using tfenv on an Intel based Mac.

**Comment by caleb15** [comment]
> Have they been removed during the upgrade?

I'm not 100% sure but I think they did get removed. In my case terraform gets installed into `/home/linuxbrew/.linuxbrew/Cellar/tfenv/2.2.3/versions`, and I don't see any other versions.

**Comment by bryanhiestand** [comment]
> > Have they been removed during the upgrade?
> 
> I'm not 100% sure but I think they did get removed. In my case terraform gets installed into `/home/linuxbrew/.linuxbrew/Cellar/tfenv/2.2.3/versions`, and I don't see any other versions.

You can set the environment variable `HOMEBREW_NO_INSTALL_CLEANUP=1` to prevent homebrew from automatically deleting old formula data when upgrading, or put the specific formulae in `HOMEBREW_NO_CLEANUP_FORMULAE`. If you use bash `export HOMEBREW_NO_CLEANUP_FORMULAE=tfenv` in `~/.bash_profile` should do the trick.  

[Housekeeping for Homebrew](https://mac.install.guide/homebrew/8.html) is a decent write-up on brew cleanup and related commands

Here are the docs from [homebrew source](https://github.com/Homebrew/brew/blob/ffc76654da12fba7d34d078fd9bf681fef65921e/Library/Homebrew/env_config.rb#L280-L285)
```ruby
      HOMEBREW_NO_INSTALL_CLEANUP:               {
        description: "If set, `brew install`, `brew upgrade` and `brew reinstall` will never automatically " \
                     "cleanup installed/upgraded/reinstalled formulae or all formulae every " \
                     "`HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS` days. Alternatively, HOMEBREW_NO_CLEANUP_FORMULAE " \
                     "allows specifying specific formulae to not clean up.",
        boolean:     true,
```

I don't know if tfenv could or should set this to true for itself?

**Comment by Zordrak** [comment]
This issue seems to contain a number of unrelated concerns.

The issue as reported is a Homebrew packaging issue. I'm afraid the Homebrew packaging is done independently by a third party; I'm not even sure how to report issues with it.

**Comment by labkey-jony** [comment]
One other workaround is to run your tfenv command via Rosetta2. I had to migrate to an M1 MacBook and some stuff that used to work on my older MacBook needed to use Rosetta2. If you setup a separate terminal window where you're running it against Rosetta2 and run the same Terraform commands like `tfenv use 0.11.15`, this will work in a Terminal window that has been configured to use Rosetta2.
