### ISSUE TITLE
Is tfenv dead?

### ISSUE THREAD

**Issue by samuel-phan** [tfutils/tfenv#399]
There is no new commit since Oct 1, 2022.

**Comment by sgametrio** [comment]
Seems like https://github.com/OJFord/tfenv/tree/impl-283 somebody is still trying to contribute 🥇 

@Zordrak Not sure if you're looking for maintainers or somebody that can help you. `tfenv` is a great tool that we all are benefitting from and we're thankful for your work!!

**Comment by SteveChurch** [comment]
@Zordrak , I would second what @sgametrio has mentioned. It looks like you could do with some additional bodies to help keep this alive. It's a brilliant tool but we're having to do some hoop jumping to overcome some of the issues open MR's fix.

**Comment by OJFord** [comment]
Yes, I do have a couple of open PRs, and am happy to work on them further as needed - but do note the difference between 'collaborator' and 'contributor' (as mine) badges on comments: the latter just means I've authored commits which have landed in master (or perhaps just this project at all, vs. my fork) - but they were committed by Zordrak, it doesn't mean I (and I don't) have write/committer access to this repo.

So my level of contribution is just 'proposing changes' really, I'm not a maintainer - stuff you see at OJFord/tfenv will only end up in tfutils/tfenv if someone who is merges it.

**Comment by OJFord** [comment]
Hi @Zordrak 

(and, sorry for the ping - @sajkat @AndrewNorman @CarlInglisBJSS @mike-winter-bjss - hoping perhaps one of you at least is one of the other two non-public tfutils org members!)

I'd be happy to help with the maintenance burden of tfenv in any way I can; I've had a couple of emails already from people assuming I have more involvement/access than I do - people are understandably keen to see some of the [fixes since v3.0.0](https://github.com/tfutils/tfenv/compare/v3.0.0...master) released (#410), and OpenTofu/the licensing debacle means a significant number of `tfenv` users are presently unable to use it, or have to weigh that aspect in their decision to switch to the forked `terraform` (#411 is a high-effort PR from OpenTofu maintainer; #409).

Feel free to contact me by email (in commits or profile) if you prefer. Cheers!

**Comment by mike-winter-bjss** [comment]
Hold fire I'll see if I can get you guys added. I originally did the port from our AWS version into Azure but don't really use it myself and as no-one else was maintaining it kinda fell by the wayside.

**Comment by Zordrak** [comment]
tfenv development is slow, as changes to the basic functionality of terraform is similarly slow and it's designed to very simply do the thing it needs to do and do it well.

**Comment by kvendingoldo** [comment]
Hello there,
[Tofuenv's](https://github.com/tofuutils/tofuenv) first stable release (v1.0) is now available! tofuenv is a fork of tfenv that only works with OpenTofu binaries. Our crew (me, @anastasiiakozlova245, @Nmishin) has been working on the fork over the past week. We worked hard to improve the usability of core [tofuenv](https://github.com/tofuutils/tofuenv) features, add some new capabilities, and, of course, fix a few bugs in the original [tfenv](https://github.com/tfutils/tfenv) program.

We'd appreciate your input and support on GitHub. Please feel free to submit issues and make contributions. Link to tofuenv: https://github.com/tofuutils/tofuenv

tofuenv can be installed manually from GitHub or via brew (for mac users).
