### ISSUE TITLE
tfenv should install version described in `terraform-version` if available.

### ISSUE THREAD

**Issue by vutoff** [tfutils/tfenv#78]
I was playing around with tfenv and discovered that if the version of terraform is missing locally, it fails. What I would suggest instead of failing to try to download that version if available remote:

```diff
diff --git a/libexec/tfenv-version-name b/libexec/tfenv-version-name
index 1d8cb74..fec4d53 100755
--- a/libexec/tfenv-version-name
+++ b/libexec/tfenv-version-name
@@ -30,8 +30,18 @@ version_exists() {
   [ -d "${TFENV_ROOT}/versions/${version}" ]
 }

+version_exists_remote() {
+  tfenv list-remote \
+  | grep "${1}"
+}
+
+
 if version_exists "${TFENV_VERSION}"; then
   echo "${TFENV_VERSION}"
 else
-  error_and_die "version \`${TFENV_VERSION}' is not installed (set by ${TFENV_VERSION_FILE})"
+  if version_exists_remote "${TFENV_VERSION}"; then
+    tfenv install "${TFENV_VERSION}"
+  else
+    error_and_die "version \`${TFENV_VERSION}' is not installed and not exists on remote. If that's a mistake, please install requested version manually (set by ${TFENV_VERSION_FILE})"
+  fi
 fi
```

**Comment by kamatama41** [comment]
@vutoff 
Thank you for your suggestion.
However, I'm not yet able to imagine your problem.  Please let me know it exactly.
I think that if a version described in `.terraform-version` is not yet installed, just running `tfenv install` before using terraform resolves it. And `tfenv-version-name` is just a command to show current Terraform version. I think installing the missing version in the command is excessive responsibility.

**Comment by espoelstra** [comment]
@abinashmeher999 why would you check every time? If you simply call `cd workspace && tfenv install && terraform` per what kamatama41 mentioned as part of your CI script it should only install if the version has changed otherwise it should detect that you already have it and simply continue. If you aren't seeing this "idempotent" behavior it sounds like something that could be improved, but trying to run `terraform` and magically having a version install if the `.terraform-version` exists is NOT a behavior I would expect as you mentioned, it would be very magic and potentially an issue if you didn't expect the job to actually install a new version.

**Comment by abinashmeher999** [comment]
@espoelstra I am doing the same thing now. I do a `tfenv install` everytime I switch to a project directory. It is idempotent and works fine.

However, think of a situation where the build service is provided as a service by one team to another. The user team is just expected to call terraform as they normally did with their own project. To make it easy for the users and not expose details of `tfenv`, they can just ask them to keep a `.terraform-version` in the project file and download all possible versions of `terraform` with `tfenv`. But again installing all versions of terraform might not be feasible for everyone.

> trying to run terraform and magically having a version install if the `.terraform-version` exists is NOT a behavior I would expect as you mentioned, it would be very magic and potentially an issue if you didn't expect the job to actually install a new version.

I totally agree with this, which is why I suggested to introduce an environment variable that would need to be set to enable this magic. So at all times the user enables this fully knowing the consequences and it is a lot cleaner.

**Comment by liamdawson** [comment]
I'd have concerns allowing this behaviour via an environment variable, to be honest — I could very easily see myself installing `tfenv`, setting it for convenience one day, and then being confused why colleague's machines didn't behave the same as mine later on. I think idempotently running `tfenv install` is a preferable mechanism for handling this, as it's guaranteed to behave consistently across machines with `tfenv`.

**Comment by abinashmeher999** [comment]
@liamdawson Good point. This would make `tfenv` behave differently on different machines.
