### ISSUE TITLE
Support provider management?

### ISSUE THREAD

**Issue by Zordrak** [tfutils/tfenv#79]
I am trying to work out the most appropriate way to support terraform providers in a CI system since they were split from terraform core in 0.10.0. I will need to provide a directory for cached provider downloads and configure terraform automation to use that directory for providers, and then to only download the provider on the first run that uses the provider.

I am wondering whether this is something we should support as part of tfenv as it is fundamentally the same implementation - the storage and use of cached versions of terraform.

@kamatama41 Do you think this is something we should support in tfenv, or something that should be left entirely to the tfenv consumer?

**Comment by matschaffer** [comment]
So far it seems like terraform itself is handling provider plugin retrieval on init.

```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (0.1.4)...
```

**Comment by Zordrak** [comment]
@matschaffer It is, however it is doing that on every init, and assuming you store your code in version control, and have a CI/CD process, you may then be downloading the provider on every checkout, which is undesirable. You could include automation to store it in a local artifact repository if you are managing one, however in the way tfenv is implemented we already locally store terraform binary versions for re-use, it seems to me to make sense to store and cache the provider versions too.. especially as terraform provides explicit support for it.

**Comment by matschaffer** [comment]
I see. Thanks for the clarification!

**Comment by Jonnymcc** [comment]
I was just thinking about this, and I wanted something like .terraform-version to enforce the provider version. Instead of requiring tfenv to do so terraform itself can constrain the provider version used and it is probably better to just let terraform handle it. https://www.terraform.io/docs/configuration/providers.html#provider-versions

**Comment by dragon788** [comment]
I believe providers and other plugins can also be installed in `~/.terraform.d/plugins/linux_amd64/` (aka `${PLATFORM}_${ARCH}`) so you could potentially manage them there and avoid the need to let `tf init` or `tf get` pull down the required providers every time. Since those plugins don't seem to be as hard locked to specific `terraform` versions it might work in your situation.

We are looking to run our terraform configs on our CI soon so I might revisit this once we establish a satisfactory workflow for not having to grab them every time.

**Comment by udondan** [comment]
This might come a bit late, but just wanted to point interested readers to [terraform-bundle](https://github.com/hashicorp/terraform/tree/master/tools/terraform-bundle). We're using this in CI to prepare a set of provider plugins to avoid re-downloading them on every run.

```hcl
terraform {
  version = "0.11.10"
}

providers {
  aws      = ["1.51.0"]
  external = ["1.0.0"]
  http     = ["1.0.1"]
  local    = ["1.1.0"]
  null     = ["1.0.0"]
  template = ["1.0.0"]
}
```

Then build a bundle with `terraform-bundle package ...`

Be aware though, that the bundle can get huuuuge.

**Comment by antonbabenko** [comment]
Since `tfenv` already uses `terraform` block to get `required_version`, it would be possible to get providers versions from there also. See [Specifying Required Provider Versions](https://www.terraform.io/docs/configuration/terraform.html#specifying-required-provider-versions).

**Comment by matschaffer** [comment]
This isn't really a tfenv thing, but I learned today that you can set `export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"`

Doing so seems to tell terraform to download providers to that directory and then the `.terraform/plugins/${PLATFORM}_${ARCH}/` are hard links back to your `TF_PLUGIN_CACHE_DIR`

Not sure if tfenv really needs to do anything additional here.

**Comment by Zordrak** [comment]
@matschaffer This is what https://github.com/tfutils/tfscaffold does.

**Comment by Zordrak** [comment]
I think for now I have to close this as outside of tfenv scope.
